version: '3.9'

name: pwii-bookworm-environment

services:
  app:
    image: llkoull/pw2-local-environment
    container_name: ${PROJECT_PREFIX}_${PROJECT_NAME}_app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - PHP_IDE_CONFIG=serverName=0.0.0.0:${XDEBUG_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./www/:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker-compose/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker-compose/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - pw2_network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: ${PROJECT_PREFIX}_${PROJECT_NAME}_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./docker-compose/mysql/:/docker-entrypoint-initdb.d/
    networks:
      - pw2_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${PROJECT_PREFIX}_${PROJECT_NAME}_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - pw2_network

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_PREFIX}_${PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www/:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pw2_network
    depends_on:
      - app

networks:
  pw2_network:
    driver: bridge